name: Building and Deploying to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
      - name: Build backend
        working-directory: ./backend
        run: |
          npm install
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Render
        env:
          deploy_url: ${{  secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl "$deploy_url"
